### Get request (auth)
GET http://localhost:5000/api/auth

### Get contact
PUT http://localhost:5000/api/contacts/1

### Post Request
POST http://localhost:5000/api/auth

### POST request
POST http://localhost:5000/api/v1/1234123412341412-123422134
Content-Type: application/json

{
   "name": "Rizwan Ishaq 1"
}